services:
  - type: web
    name: me-moo-stock
    runtime: node
    region: oregon
    rootDir: backend
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: FRONTEND_URL
        fromService:
          name: me-moo-stock
          type: web
          property: host
